CREATE TABLE IF NOT EXISTS CONTENT_MASTER (
  COT_ID char(36) PRIMARY KEY,
  CONTENT_ID varchar(12) UNIQUE,
  CONTENT_TYPE int(11) DEFAULT NULL,
  CONTENT_STATUS tinyint(4) DEFAULT NULL,
  TITLE varchar(600) DEFAULT NULL,
  DISPLAY_TITLE varchar(1000) DEFAULT NULL,
  READ_COUNT int(11) DEFAULT NULL,
  SHOW_FLAG int(11) DEFAULT NULL,
  CREATE_USR_ID char(36) DEFAULT NULL,
  CREATE_DATE datetime DEFAULT NULL,
  MODIFIED_DATE datetime DEFAULT NULL,
  DEPT varchar(50) DEFAULT NULL,
  DEPT_VIEW varchar(50) DEFAULT NULL,
  TEL varchar(100) DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS DATABASE_MASTER (
  COT_ID char(36) PRIMARY KEY,
  BOOK_TOUR tinyint(4) DEFAULT NULL,
  HOMEPAGE text DEFAULT NULL,
  ADMIN_NAME text DEFAULT NULL,
  ADMIN_TEL varchar(300) DEFAULT NULL,
  ADMIN_FAX text DEFAULT NULL,
  ADMIN_EMAIL varchar(200) DEFAULT NULL,
  SET_STATUS varchar(2000) DEFAULT NULL,
  FIRST_IMAGE char(36) DEFAULT NULL,
  FIRST_IMAGE2 char(36) DEFAULT NULL,
  AREA_CODE int(11) DEFAULT NULL,
  SIGUGUN_CODE int(11) DEFAULT NULL,
  DONG_CODE int(11) DEFAULT NULL,
  CAT1 varchar(12) DEFAULT NULL,
  CAT2 varchar(12) DEFAULT NULL,
  CAT3 varchar(12) DEFAULT NULL,
  ADDR1 varchar(400) DEFAULT NULL,
  ADDR2 varchar(400) DEFAULT NULL,
  ZIP_CODE varchar(12) DEFAULT NULL,
  MAPX varchar(30) DEFAULT NULL,
  MAPY varchar(30) DEFAULT NULL,
  WGSX decimal(38,10) DEFAULT NULL,
  WGSY decimal(38,10) DEFAULT NULL,
  MLEVEL varchar(10) DEFAULT NULL,
  OVER_VIEW text DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS ACCOMMODATION_INTRO (
  COT_ID char(36) NOT NULL,
  ACCOM_COUNT varchar(1500) DEFAULT NULL,
  BENIKIA tinyint(4) DEFAULT NULL,
  CHECK_IN_TIME varchar(1000) DEFAULT NULL,
  CHECK_OUT_TIME varchar(1000) DEFAULT NULL,
  CHK_COOKING varchar(1000) DEFAULT NULL,
  FOOD_PLACE text DEFAULT NULL,
  GOOD_STAY tinyint(4) DEFAULT NULL,
  HANOK tinyint(4) DEFAULT NULL,
  CONTACT_INFO text DEFAULT NULL,
  PARKING text DEFAULT NULL,
  PICKUP varchar(500) DEFAULT NULL,
  ROOM_COUNT varchar(1000) DEFAULT NULL,
  RESERVATION text DEFAULT NULL,
  RESERVATION_URL varchar(1000) DEFAULT NULL,
  ROOM_TYPE text DEFAULT NULL,
  SCALE text DEFAULT NULL,
  SUB_FACILITY text DEFAULT NULL,
  BARBECUE tinyint(4) DEFAULT NULL,
  BEAUTY tinyint(4) DEFAULT NULL,
  BICYCLE tinyint(4) DEFAULT NULL,
  COMPFIRE tinyint(4) DEFAULT NULL,
  FITNESS tinyint(4) DEFAULT NULL,
  KARAOKE tinyint(4) DEFAULT NULL,
  PUBLIC_BATH tinyint(4) DEFAULT NULL,
  PUBLIC_PC tinyint(4) DEFAULT NULL,
  SAUNA tinyint(4) DEFAULT NULL,
  SEMINAR tinyint(4) DEFAULT NULL,
  SPORTS tinyint(4) DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS COURSE_INTRO (
  COT_ID char(36) NOT NULL,
  DISTANCE varchar(100) DEFAULT NULL,
  TAKE_TIME varchar(100) DEFAULT NULL,
  CONTACT_INFO text DEFAULT NULL,
  SCHEDULE text DEFAULT NULL,
  THEME varchar(40) DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS CULTURAL_FACILITIES_INTRO (
  COT_ID char(36) NOT NULL,
  ACCOM_COUNT varchar(1500) DEFAULT NULL,
  SCALE text DEFAULT NULL,
  SPENDTIME text DEFAULT NULL,
  CHK_BABY_CARRIAGE varchar(200) DEFAULT NULL,
  CHK_CREDITCARD varchar(100) DEFAULT NULL,
  CHK_PET varchar(200) DEFAULT NULL,
  DISCOUNT_INFO text DEFAULT NULL,
  INFO_CENTER varchar(4000) DEFAULT NULL,
  PARKING text DEFAULT NULL,
  PARKING_FEE text DEFAULT NULL,
  REST_DATE varchar(1500) DEFAULT NULL,
  USE_FEE text DEFAULT NULL,
  USE_TIME text DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS EATERY_INTRO (
  COT_ID char(36) NOT NULL,
  CHK_CREDITCARD varchar(100) DEFAULT NULL,
  DISCOUNT_INFO text DEFAULT NULL,
  FIRST_MENU text DEFAULT NULL,
  CONTACT_INFO text DEFAULT NULL,
  KIDS_FACILITY text DEFAULT NULL,
  OPEN_DATE varchar(300) DEFAULT NULL,
  OPEN_TIME text DEFAULT NULL,
  PACKING text DEFAULT NULL,
  PARKING text DEFAULT NULL,
  RESERVATION text DEFAULT NULL,
  REST_DATE varchar(1500) DEFAULT NULL,
  SCALE text DEFAULT NULL,
  SEAT text DEFAULT NULL,
  SMOKING varchar(200) DEFAULT NULL,
  TREAT_MENU text DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS FESTIVAL_INTRO (
  COT_ID char(36) NOT NULL,
  SCALE text DEFAULT NULL,
  SPEND_TIME varchar(2000) DEFAULT NULL,
  AGE_LIMIT varchar(2000) DEFAULT NULL,
  BOOKING_PLACE text DEFAULT NULL,
  DISCOUNT_INFO text DEFAULT NULL,
  EVENT_END_DATE char(8) DEFAULT NULL,
  EVENT_HOMEPAGE varchar(1000) DEFAULT NULL,
  EVENT_PLACE varchar(500) DEFAULT NULL,
  EVENT_START_DATE char(8) DEFAULT NULL,
  FESTIVAL_GRADE varchar(100) DEFAULT NULL,
  PLACE_INFO text DEFAULT NULL,
  PLAY_TIME text DEFAULT NULL,
  PROGRAM mediumtext DEFAULT NULL,
  SPONSOR1 varchar(800) DEFAULT NULL,
  SPONSOR1_TEL varchar(300) DEFAULT NULL,
  SPONSOR2 varchar(300) DEFAULT NULL,
  SPONSOR2_TEL varchar(300) DEFAULT NULL,
  SUB_EVENT text DEFAULT NULL,
  USE_FEE text DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS LEPORTS_INTRO (
  COT_ID char(36) NOT NULL,
  ACCOM_COUNT varchar(1500) DEFAULT NULL,
  CHK_BABY_CARRIAGE varchar(200) DEFAULT NULL,
  CHK_CREDITCARD varchar(100) DEFAULT NULL,
  CHK_PET varchar(200) DEFAULT NULL,
  EXP_AGE_RANGE varchar(500) DEFAULT NULL,
  INFO_CENTER varchar(4000) DEFAULT NULL,
  OPEN_PERIOD text DEFAULT NULL,
  PARKING_FEE text DEFAULT NULL,
  PARKING text DEFAULT NULL,
  RESERVATION text DEFAULT NULL,
  REST_DATE varchar(1500),
  SCALE text DEFAULT NULL,
  USE_FEE text DEFAULT NULL,
  USE_TIME text DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS SHOPPING_INTRO (
  COT_ID char(36) NOT NULL,
  CHK_BABY_CARRIAGE varchar(200) DEFAULT NULL,
  CHK_CREDITCARD varchar(100) DEFAULT NULL,
  CHK_PET varchar(200) DEFAULT NULL,
  CULTURE_CENTER varchar(1000) DEFAULT NULL,
  FAIR_DAY varchar(100) DEFAULT NULL,
  CONTACT_INFO text DEFAULT NULL,
  OPEN_DATE varchar(300) DEFAULT NULL,
  OPEN_TIME text DEFAULT NULL,
  PARKING text DEFAULT NULL,
  REST_DATE varchar(1500) DEFAULT NULL,
  REST_ROOM varchar(2000) DEFAULT NULL,
  SALE_ITEM text DEFAULT NULL,
  SALE_ITEM_COST text DEFAULT NULL,
  SCALE text DEFAULT NULL,
  SHOP_GUIDE longtext DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS TOURIST_SPOT_INTRO (
  COT_ID char(36) NOT NULL,
  ACCOM_COUNT varchar(1500) DEFAULT NULL,
  CHK_BABY_CARRIAGE varchar(200) DEFAULT NULL,
  CHK_CREDITCARD varchar(100) DEFAULT NULL,
  CHK_PET varchar(200) DEFAULT NULL,
  EXP_AGE_RANGE varchar(500) DEFAULT NULL,
  EXP_GUIDE text DEFAULT NULL,
  HERITAGE1 tinyint(4) DEFAULT NULL,
  HERITAGE2 tinyint(4) DEFAULT NULL,
  HERITAGE3 tinyint(4) DEFAULT NULL,
  INFO_CENTER varchar(4000) DEFAULT NULL,
  OPEN_DATE varchar(300) DEFAULT NULL,
  PARKING text DEFAULT NULL,
  REST_DATE varchar(1500),
  USE_SEASON varchar(500),
  USE_TIME text DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS ACCOMMODATION_INFO (
  COT_ID char(36) NOT NULL,
  ROOM_CODE varchar(12) DEFAULT NULL,
  ROOM_TITLE varchar(192) DEFAULT NULL,
  ROOM_SIZE1 varchar(50) DEFAULT NULL,
  ROOM_COUNT varchar(50) DEFAULT NULL,
  ROOM_BASE_COUNT varchar(50) DEFAULT NULL,
  ROOM_MAX_COUNT varchar(50) DEFAULT NULL,
  ROOM_OFF_SEASON_MIN_FEE1 varchar(50) DEFAULT NULL,
  ROOM_OFF_SEASON_MIN_FEE2 varchar(50) DEFAULT NULL,
  ROOM_PEAK_SEASON_MIN_FEE1 varchar(50) DEFAULT NULL,
  ROOM_PEAK_SEASON_MIN_FEE2 varchar(50) DEFAULT NULL,
  ROOM_INTRO text DEFAULT NULL,
  ROOM_BATH_FACILITY varchar(5) DEFAULT NULL,
  ROOM_BATH varchar(5) DEFAULT NULL,
  ROOM_HOME_THEATER varchar(5) DEFAULT NULL,
  ROOM_AIR_CONDITIONER varchar(5) DEFAULT NULL,
  ROOM_TV varchar(5) DEFAULT NULL,
  ROOM_PC varchar(5) DEFAULT NULL,
  ROOM_CABLE varchar(5) DEFAULT NULL,
  ROOM_INTERNET varchar(5) DEFAULT NULL,
  ROOM_REFRIGERATOR varchar(5) DEFAULT NULL,
  ROOM_TOILETRIES varchar(5) DEFAULT NULL,
  ROOM_SOFA varchar(5) DEFAULT NULL,
  ROOM_COOK varchar(5) DEFAULT NULL,
  ROOM_TABLE varchar(5) DEFAULT NULL,
  ROOM_HAIRDRYER varchar(5) DEFAULT NULL,
  ROOM_SIZE2 varchar(50) DEFAULT NULL,
  ROOM_IMG1 char(36) DEFAULT NULL,
  ROOM_IMG2 char(36) DEFAULT NULL,
  ROOM_IMG3 char(36) DEFAULT NULL,
  ROOM_IMG4 char(36) DEFAULT NULL,
  ROOM_IMG5 char(36) DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS COURSE_INFO (
  COT_ID char(36) NOT NULL,
  SUB_CONTENT_ID varchar(36) DEFAULT NULL,
  SUB_DETAIL_IMG char(36) DEFAULT NULL,
  SUB_DETAIL_OVERVIEW text DEFAULT NULL,
  SUB_NAME varchar(600) DEFAULT NULL,
  SUB_NUM tinyint(4) DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS DETAIL_INFO (
  COT_ID char(36) NOT NULL,
  FLD_GUBUN int(11) DEFAULT NULL,
  DISPLAY_TITLE varchar(1000) DEFAULT NULL,
  CONTENT_BODY longtext DEFAULT NULL,
  SERIAL_NUM mediumint(9) DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS OTHER_DEPARTMENT_CONTENT (
  COT_ID char(36) NOT NULL,
  OTD_ID char(36) NOT NULL
);

CREATE TABLE IF NOT EXISTS CONTENT_TAGS (
  TAG_ID char(36) NOT NULL,
  COT_ID char(36) NOT NULL,
  MASTER_TAG int(11) DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS IMAGE (
  IMG_ID char(36) PRIMARY KEY,
  COT_ID char(36) NOT NULL,
  IMAGE_PATH varchar(350) DEFAULT NULL,
  IMAGE_DESCRIPTION varchar(300) DEFAULT NULL,
  IS_THUBNAIL int(1) DEFAULT 0,
  MD5 varchar(100) DEFAULT NULL,
  URL text NOT NULL
);
